version: 2.1
workflows:
  version: 2
  bookshop_cicd_workflow:
    jobs:
      - build_and_test

jobs:
  build_and_test:
    docker:
      - image: gradle:alpine
    steps:
      - checkout
      - run: ./gradlew build
      - persist_to_workspace:
          root: ./
          paths:
            - build/libs/bookshop-1.0.0.jar
      - store_test_results:
          path: build/test-results