CREATE TABLE users
(id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 name TEXT NOT NULL,
 author TEXT NOT NULL,
 price TEXT NOT NULL,
 books_count INTEGER,
 isbn TEXT,
 publication_year INTEGER,
 average_rating float8
PRIMARY KEY (id));