CREATE TABLE orders (
    id BIGINT generated BY DEFAULT AS identity,
    user_name text NOT NULL,
    order_date DATE NOT NULL,
    amount FLOAT8 NOT NULL,
    PRIMARY KEY (id));

CREATE TABLE ordered_items (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	order_id BIGINT,
	book_id BIGINT,
	quantity INT NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_orders_1
		FOREIGN KEY(order_id)
			REFERENCES orders(id),
	CONSTRAINT fk_books_1
		FOREIGN KEY(book_id)
			REFERENCES books(id)
);

CREATE TABLE delivery_info (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	order_id BIGINT,
	name TEXT,
	email TEXT,
	mobile_number BIGINT,
	address TEXT,
	country TEXT,
	PRIMARY KEY (id),
	CONSTRAINT fk_orders_2
		FOREIGN KEY (order_id)
			REFERENCES orders (id)
);

-- DROP TABLE ordered_items;
-- DROP TABLE delivery_info;
-- DROP TABLE orders;